---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_macos: true

dotfiles_repo: https://github.com/tomtastic/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_files:
  - .zshrc
  - .oh-my-zsh
  - .gitignore
  - .gitconfig
  - .vimrc
  - .vim
  - .osx

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - buo/cask-upgrade

homebrew_installed_packages:
  - ack
  # - ansible # Installed via Pip.
  - azure-cli
  - autoconf
  - autogen
  - automake
  # - bash-completion
  - binwalk
  - cmake
  # - cowsay
  - ctags
  - certigo
  - distribution
  - dos2unix
  # - doxygen
  - dtc
  - exiftool
  - exploitdb
  - fd
  - ffuf
  - flashrom
  - fswatch
  - gawk
  # - gettext
  # - gifsicle
  # - git
  # - go
  # - gpg
  - hexyl
  # - hub
  # - httpie
  # - iperf
  - jq
  # - libevent
  - libev
  - lsusb
  - mas
  # - mcrypt
  - nmap
  # - node
  # - nvm
  - openjdk@11
  - openocd --HEAD
  # - openssl
  - pandoc
  - perl
  # - php
  - pngcrush
  # - pv
  - pylint
  - python3
  - qemu
  - rbspy
  - ruby
  - rust
  # - readline
  - shellcheck
  - sleuthkit
  # - ssh-copy-id
  - sphinx-doc
  # - sqlite
  - squashfs
  - telnet
  - testdisk
  - the_silver_searcher
  - tree
  - upx
  - vim
  - watch
  - wget
  # - wrk
  - yamllint
  - yubikey-personalization


homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - adoptopenjdk
  - avibrazil-rdm
  - bettertouchtool
  - blockblock
  - burp-suite
  - caffeine
  - calibre
  # Citrix needs a manual download now :<
  # brew cask install https://www.corecode.io/macupdater/casks/citrix-workspace.rb
  # corectl cask no longer exists ?
  #- corectl
  - coconutbattery
  - cutter
  - dash
  - detectx-swift
  - gimp
  - doomsday-engine
  - doxie
  - ghidra
  - google-chrome
  - gpg-suite
  - grandperspective
  - handbrake-nightly
  - hex-fiend-beta
  # - intel-power-gadget
  - iterm2
  - kextviewr
  - key-codes
  - keepassxc
  - kindle-previewer
  - knockknock
  - macs-fan-control
  - monitorcontrol
  - netiquette
  - obs
  - omnifocus
  - oversight
  - postman
  - reikey
  - scroll-reverser
  - sdformatter
  - send-to-kindle
  - signal
  - slack
  - db-browser-for-sqlite
  - taskexplorer
  - textual
  - tor-browser
  - tunnelblick-beta
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - vlc
  - vmware-fusion
  - vnc-viewer
  # The whatsapp-helper is just too annoying and electron apps don't deserve admin rights
  # - whatsapp
  - whatsyoursign
  - wireshark
  - xact
  - yubico-yubikey-manager
  # - chromedriver
  # - docker
  # - dropbox
  # - firefox
  # - licecap
  # - limechat
  # - sequel-pro
  # - skitch
  # - sublime-text
  # - transmit

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - {id: 497799835, name: "Xcode"}
  - {id: 409201541, name: "Pages"}
  - {id: 409203825, name: "Numbers"}
  - {id: 409183694, name: "Keynote"}
  - {id: 408981434, name: "iMovie"}
  - {id: 1037126344, name: "Apple Configurator 2"}
  - {id: 425424353, name: "The Unarchiver"}
  - {id: 1160435653, name: "AutoMounter"}
  - {id: 928871589, name: "noizio"}
  - {id: 1381004916, name: "discovery-dns-sd-browser"}
  # - { id: 443987910,  name: "1Password" }
  # - { id: 557168941,  name: "Tweetbot" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
