---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Read customisations
      include_vars: "{{ item }}"
      with_fileglob:
        - ./config.yml
      tags: ['always']
    - name: Get latest elliotweiser/ansible-osx-command-line-tools from github
      git:
        repo: 'git@github.com:elliotweiser/ansible-osx-command-line-tools.git'
        dest: ~/src/ansible/roles/elliotweiser.osx-command-line-tools
        version: master
        update: yes
      tags: ['homebrew']
    - name: Get latest geerlingguy/ansible-role-homebrew from github
      git:
        repo: 'git@github.com:geerlingguy/ansible-role-homebrew.git'
        dest: ~/src/ansible/roles/ansible-role-homebrew
        version: master
        update: yes
      tags: ['homebrew']
    - name: Get latest geerlingguy/ansible-role-mas from github
      git:
        repo: 'git@github.com:geerlingguy/ansible-role-mas.git'
        dest: ~/src/ansible/roles/ansible-role-mas
        version: master
        update: yes
      tags: ['mas,homebrew']
    - name: Get latest tomtastic/ansible-role-dotfiles from github
      git:
        repo: 'git@github.com:tomtastic/ansible-role-dotfiles.git'
        dest: ~/src/ansible/roles/ansible-role-dotfiles
        version: master
        update: yes
      tags: ['dotfiles']
    - name: Get latest tomtastic/ansible-role-mbp from github
      git:
        repo: 'git@github.com:tomtastic/ansible-role-mbp.git'
        dest: ~/src/ansible/roles/ansible-role-mbp
        version: master
        update: yes
      tags: ['macos']

  tasks:
    - name: ansible-role-homebrew
      include_role:
        name: ansible-role-homebrew
      tags: ['homebrew']

    - name: ansible-role-mas
      include_role:
        name: ansible-role-mas
      when: mas_installed_apps
      tags: ['mas']

    - name: ansible-role-dotfiles
      include_role:
        name: ansible-role-dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

    - name: ansible-role-mbp
      include_role:
        name: ansible-role-mbp
      when: configure_macos
      tags: ['macos']

