---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Read customisations
      include_vars: "{{ item }}"
      with_fileglob:
        - ./config.yml
      tags: ['always']
    - name: Get the latest role from github
      git:
        repo: 'git@github.com:tomtastic/ansible-role-mbp.git'
        dest: ~/src/ansible/roles/ansible-role-mbp
        version: master
        update: yes
      tags: ['always']

  roles:
      - role: ansible-role-mbp
        tags: ['homebrew','mas','macos']

