---
- hosts: localhost
  connection: local
  gather_facts: yes

  pre_tasks:
    - name: Get the latest role from github
      git:
        repo: 'git@github.com:tomtastic/ansible-role-mbp.git'
        dest: ~/src/ansible/roles/
        version: master
        update: no
        keyfile: ~/.ssh/github
        verify_commit: yes

  #  role:
  #  - ansible-role-mbp

