---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Read customisations
      include_vars: "{{ item }}"
      with_fileglob:
        - ./config.yml
      tags: ['always']

  roles:
    - name: Apply role geerlingguy.homebrew
      role: elliotweiser.osx-command-line-tools
      tags: ['homebrew']

    - name: Apply role geerlingguy.mas
      role: geerlingguy.homebrew
      tags: ['homebrew']

    - name: Apply role geerlingguy.mas
      role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

    - name: Apply role tomtastic.dotfiles
      role: tomtastic.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

    - name: Apply role tomtastic.mbp
      role: tomtastic.macos
      when: configure_macos
      tags: ['macos']

