---
- hosts: localhost
  connection: local
  gather_facts: yes

  pre_tasks:
    - name: Get the latest role from github
      git:
        repo: 'git@github.com:tomtastic/ansible-role-mbp.git'
        dest: ~/src/ansible/roles/ansible-role-mbp
        version: master
        update: yes

  roles:
  - ansible-role-mbp

